services:
  keycloak-db:
    image: postgres:16-alpine
    container_name: bluefox-iam-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iam-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: bluefox-iam-server
    # Trocado para 'start' e removido o import automático se não quiser sobrescrever sempre
    command: ${KC_COMMAND}
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME} # Domínio Real
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true" # O Nginx fala HTTP com o container na rede interna
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /auth
    # Removi o mapeamento de portas 8080:8080 se você for usar APENAS via Nginx
    # Mas se quiser testar antes, pode manter.
    ports:
      - "${KC_PORT_INNER}:${KC_PORT_OUTER}"
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./themes:/opt/keycloak/themes
    depends_on:
      - keycloak-db
    networks:
      - iam-network
      - shared-net

networks:
  iam-network:
    driver: bridge
  shared-net:
    name: ${DOCKER_NETWORK}
    external: true

volumes:
  postgres_data:
